version: '3.8'

services:
  frontend:
    build:
      context: ./frondend-foodorder
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend-foodorder
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/foodorder
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - upload-file.base-uri=file:///uploads/
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - ./upload-docker/:/uploads/

  mysql:
    image: mysql:8.0.41 # Specify exact version to avoid mismatches
    restart: always
    environment:
      - MYSQL_DATABASE=foodorder # No colon, consistent with list format
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
